export const DATE_FORMATS = {
  TIME_DATE: 'HH:mm DD/MM/YYYY',
  MONTH_DAY: 'MMM DD',
  DAY_MONTH: 'DD MMM',
  DAY_MONTH_YEAR: 'DD MMM YYYY',
  DAY_MONTH_YEAR_SLASH: 'DD/MM/YYYY',
  FMONTH_DAY_YEAR: 'MMMM DD, YYYY',
  DATE_TIME: 'DD/MM HH:mm',
  DATE_FULL_TIME: 'DD/MM/YYYY HH:mm',
  DAY: 'DD',
  MONTH: 'MMM',
  HOUR_MINUTE: 'HH:mm',
  LOCAL_DATE: 'LLL',
};
